# Site settings
title: Programmer X
email: carmack.shi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a little programmer loves hacking...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://metacpp.github.io" # the base hostname & protocol for your site
twitter_username: metacpp
github_username:  metacpp

# Build settings
markdown: kramdown


